backend:
  name: git-gateway

media_folder: "site/static/img"
public_folder: "img"

collections:
  - name: "post"
    label: "Post"
    folder: "site/content/post"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [
            {label: Heading, name: title, widget: text},
            {label: Image, name: img, widget: image},
            {label: Subtitle, name: subtitle, widget: text}
            ]}
          - {label: About Us, name: wrapper, widget: object, fields: [
            {label: Title, name: title, widget: text},
            {label: Italic, name: italic, widget: text},
            {label: Image, name: img, widget: image},
            {label: Content, name: content, widget: list, fields:[
            {label: Paragraph, name: paragraph, widget: text}
            ]}
            ]}
          - {label: Philosofy, name: philosofy, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Image, name: img, widget: image},
            {label: Content, name: content, widget: markdown}
            ]}
          - {label: Koliving, name: koliving, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Block, name: block, widget: list, fields:[
            {label: Image, name: img, widget: image},
            {label: Name, name: name, widget: string},
            {label: Country, name: country, widget: string},
            {label: Content, name: content, widget: markdown}
            ]}
            ]}
          - {label: Plan, name: plan, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Image, name: img, widget: image},
            {label: Content, name: content, widget: markdown}
            ]}
      - file: "site/content/test/_index.md"
        label: "Test Page"
        name: "test"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [
            {label: Heading, name: title, widget: text},
            {label: Image, name: img, widget: image},
            {label: Subtitle, name: subtitle, widget: text}
            ]}
          - {label: About Us, name: wrapper, widget: object, fields: [
            {label: Title, name: title, widget: text},
            {label: Italic, name: italic, widget: text},
            {label: Image, name: img, widget: image},
            {label: Content, name: content, widget: list, fields:[
            {label: Paragraph, name: paragraph, widget: text}
            ]}
            ]}
          - {label: Philosofy, name: philosofy, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Image, name: img, widget: image},
            {label: Content, name: content, widget: markdown}
            ]}
          - {label: Plan, name: plan, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Image, name: img, widget: image},
            {label: Content, name: content, widget: markdown}
            ]}
      - file: "site/data/service.yaml"
        label: "Test Page"
        name: "test"
        fields:
          - {label: Koliving, name: koliving, widget: object, fields: [
            {label: Title, name: title, widget: string},
            {label: Block, name: block, widget: list, fields:[
            {label: Image, name: img, widget: image},
            {label: Name, name: name, widget: string},
            {label: Country, name: country, widget: string},
            {label: Content, name: content, widget: markdown}
            ]}
            ]}
